version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_travel
    container_name: travel_booking_django
    ports:
      - "8008:8008"
    volumes:
      - Django_project:/my_code/Django_project
    env_file:
      - .env
    networks:
      - django_network
    depends_on:
      - server

  server:
    image: nginx:alpine
    container_name: nginx_con_django
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      - django_network

volumes:
  Django_project:

networks:
  django_network:
    driver: bridge
