# Generated by Django 5.0.2 on 2024-03-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coonoor_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_videous')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manjoor_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_videous')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='masinagudi_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_videous')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ooty_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_videous')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='owl_combo_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('title', models.CharField(max_length=100)),
                ('places', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=250)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_videous')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='welcome_page_image_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('name', models.CharField(default='first', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='welcome_page_image_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('name', models.CharField(default='secont', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='welcome_page_image_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_photos')),
                ('name', models.CharField(default='third', max_length=100)),
            ],
        ),
    ]
