# Generated by Django 5.0.2 on 2024-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comb_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='combo', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('places', models.CharField(max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='coonoor_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='coonoor', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='manjoor_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='manjoor', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='masinagudi_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='masinagudi', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ooty_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='ooty', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='other_package_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('pick_up', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('package', models.CharField(default='combo', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('places', models.CharField(max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at_D_T', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
